"""Generates the service landing pages (English + Arabic) from tools/service_content.py:
    services/index.html, services/<slug>.html, services/pos-machines.html  (and the same under ar/)
Run:  python tools/build_service_pages.py   (then python tools/build_sitemap.py and python tools/audit_seo.py)
"""
import json
from html import escape, unescape
from urllib.parse import quote

from build_product_pages import PHONE, PRODUCTS, ROOT, SITE, UI as PUI, WA_ICON, WHATSAPP, footer, header, localize, logo_tile, text_only
from service_content import PORTFOLIO, POS_MACHINES, SERVICES, UI

ALL = SERVICES + [POS_MACHINES]
HREFLANG_EN = ('en', 'en-AE', 'en-SA', 'en-IN')
HREFLANG_AR = ('ar', 'ar-AE', 'ar-SA')
COUNTRIES = {'all': ['United Arab Emirates', 'Saudi Arabia', 'India'], 'uae': ['United Arab Emirates']}


def url(slug, lang):
    return f'{SITE}/{"ar/" if lang == "ar" else ""}services/{slug + ".html" if slug else ""}'


def wa(text):
    return f'https://wa.me/{WHATSAPP}?text={quote(unescape(text))}'


def head(lang, root, slug, title, desc, keywords, image, ld):
    hreflang = '\n'.join(
        [f'    <link rel="alternate" hreflang="{h}" href="{url(slug, "en")}">' for h in HREFLANG_EN] +
        [f'    <link rel="alternate" hreflang="{h}" href="{url(slug, "ar")}">' for h in HREFLANG_AR] +
        [f'    <link rel="alternate" hreflang="x-default" href="{url(slug, "en")}">'])
    fonts = ('family=Chakra+Petch:wght@500;600;700&family=IBM+Plex+Sans:wght@400;500;600'
             + ('&family=IBM+Plex+Sans+Arabic:wght@400;500;600;700&family=Noto+Kufi+Arabic:wght@600;700;800' if lang == 'ar' else '')
             + '&family=JetBrains+Mono:wght@400;500;700&display=swap')
    title, desc = escape(unescape(title)), escape(unescape(desc))
    return f'''<!DOCTYPE html>
<html lang="{lang}" dir="{'rtl' if lang == 'ar' else 'ltr'}">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Generated by tools/build_service_pages.py - edit tools/service_content.py, not this file. -->
    <title>{title}</title>
    <meta name="description" content="{desc}">
    <meta name="keywords" content="{escape(unescape(keywords))}">
    <meta name="robots" content="index, follow, max-image-preview:large">
    <meta name="theme-color" content="#07080a">
    <link rel="canonical" href="{url(slug, lang)}">
{hreflang}
    <meta name="geo.region" content="AE-AZ">
    <meta name="geo.placename" content="Abu Dhabi">
    <link rel="icon" href="{root}favicon.ico" sizes="48x48">
    <link rel="icon" type="image/png" sizes="48x48" href="{root}images/favicon-48.png">
    <link rel="icon" type="image/png" sizes="192x192" href="{root}images/favicon.png">
    <link rel="apple-touch-icon" href="{root}images/apple-touch-icon.png">
    <link rel="manifest" href="{root}site.webmanifest">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="Anqah Tech">
    <meta property="og:url" content="{url(slug, lang)}">
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{desc}">
    <meta property="og:image" content="{image}">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta property="og:locale" content="{'ar_AE' if lang == 'ar' else 'en_AE'}">
    <meta property="og:locale:alternate" content="{'en_AE' if lang == 'ar' else 'ar_AE'}">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="{title}">
    <meta name="twitter:description" content="{desc}">
    <meta name="twitter:image" content="{image}">
    <script type="application/ld+json">
{json.dumps(ld, ensure_ascii=False, indent=2)}
    </script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?{fonts}" rel="stylesheet">
    <link rel="stylesheet" href="{root}style.css">
</head>
'''


def tail(lang, root, switch_href):
    pdf = f'{root}downloads/Anqah-Tech-Company-Profile{"-AR" if lang == "ar" else ""}.pdf'
    label = PUI[lang]['profile_dl']
    return f'''
{footer(lang, root, switch_href, product_dir='../products/')}

    <a class="fab-pdf" href="{pdf}" download aria-label="{label}" title="{label}">
        <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M12 11v6m0 0-3-3m3 3 3-3"/></svg>
    </a>
    <a class="fab-wa" href="https://wa.me/{WHATSAPP}" target="_blank" rel="noopener" aria-label="{PUI[lang]['chat']}">
        {WA_ICON}
    </a>

    <script src="{root}script.js"></script>
</body>

</html>
'''


def org():
    return {'@type': 'Organization', '@id': f'{SITE}/#org', 'name': 'Anqah Tech', 'url': f'{SITE}/'}


def breadcrumbs(lang, items):
    return {'@type': 'BreadcrumbList', 'itemListElement': [
        {'@type': 'ListItem', 'position': i, 'name': text_only(n), 'item': u} for i, (n, u) in enumerate(items, 1)]}


def areas(s, t):
    keys = ['uae', 'ksa', 'ind'] if s['region'] == 'all' else ['uae']
    cards = ''.join(f'<article class="area hud reveal"><h3>{t[k][0]}</h3><p class="cities">{t[k][1]}</p></article>' for k in keys)
    return f'''
        <section class="section">
            <header class="sec-head reveal"><span class="num">// 03</span><div><h2>{t['areas']}</h2><p>{t['areas_all'] if s['region'] == 'all' else t['areas_uae']}</p></div></header>
            <div class="areas{' areas-one' if len(keys) == 1 else ''}">{cards}</div>
        </section>'''


def related(s, lang, root, t):
    if not s.get('related'):
        return ''
    p = localize(next(x for x in PRODUCTS if x['slug'] == s['related']), lang)
    return (f'<a class="pd-other hud sv-related" href="../products/{p["slug"]}.html">{logo_tile(p, root, lang, "pd-other-logo")}'
            f'<span><small>{t["related"]}</small><b>{p["name"]}</b></span><span class="arr">&rarr;</span></a>')


def hardware_block(lang, root, t):
    sello = localize(next(x for x in PRODUCTS if x['slug'] == 'sello'), lang)
    hw = sello['hardware']
    figs = ''.join(f'<figure class="shot reveal"><img src="{root}images/products/pos-hardware/{f}" alt="{ti}" width="800" height="600" loading="lazy">'
                   f'<figcaption><b>{ti}</b>{c}</figcaption></figure>' for f, ti, c in hw['items'])
    incl = ''.join(f'<li>{i}</li>' for i in hw['includes'])
    return f'''
        <section class="section">
            <header class="sec-head reveal"><span class="num">// 01</span><div><h2>{t['hw_h']}</h2></div></header>
            <div class="gallery hw-gallery">{figs}</div>
            <div class="hw-incl hud reveal"><span class="tag">{t['incl']}</span><ul>{incl}</ul></div>
        </section>'''


def portfolio_block(lang, root, num):
    """Client work case studies (the same markup is copied into the home pages)."""
    cards = ''
    for w in PORTFOLIO:
        c = w[lang]
        a, b, m = (f'{root}images/portfolio/{f}' for f in w['images'])
        built = ''.join(f'<li>{x}</li>' for x in c['built'])
        cards += f'''
            <article class="case hud reveal">
                <div class="case-shots">
                    <img class="case-main" src="{a}" alt="{c['client']} website home page" width="1200" height="750" loading="lazy">
                    <img class="case-second" src="{b}" alt="{c['client']} website business verticals" width="1200" height="750" loading="lazy">
                    <img class="case-phone" src="{m}" alt="{c['client']} website on mobile" width="390" height="844" loading="lazy">
                </div>
                <div class="case-copy">
                    <span class="tag">{c['meta']}</span>
                    <h3>{c['client']}</h3>
                    <p>{c['about']}</p>
                    <ul class="pd-list">{built}</ul>
                    <a class="btn btn-line" href="{w['url']}" target="_blank" rel="noopener">{c['visit']} <span class="arr">&#8599;</span></a>
                </div>
            </article>'''
    first = PORTFOLIO[0][lang]
    return f'''
        <section class="section" id="work">
            <header class="sec-head reveal"><span class="num">// {num}</span><div><h2>{first['h']}</h2></div></header>{cards}
        </section>'''


def service_page(s, lang):
    t, c = UI[lang], s[lang]
    root = '../../' if lang == 'ar' else '../'
    slug = s['slug']
    u = url(slug, lang)
    home = f'{SITE}/{"ar/" if lang == "ar" else ""}'
    switch_href = f'../../services/{slug}.html' if lang == 'ar' else f'../ar/services/{slug}.html'
    is_pos = slug == 'pos-machines'
    image = f'{SITE}/images/og/og-sello.jpg' if slug in ('pos-machines', 'pos-systems') else f'{SITE}/images/og/og-home.jpg'
    ld = {'@context': 'https://schema.org', '@graph': [
        {'@type': 'Service', '@id': f'{u}#service', 'name': text_only(c['name']), 'serviceType': text_only(c['name']),
         'description': text_only(c['description']), 'url': u, 'provider': org(),
         'areaServed': [{'@type': 'Country', 'name': n} for n in COUNTRIES[s['region']]]},
        breadcrumbs(lang, [(t['home'], home), (t['services'], url('', lang)), (c['name'], u)]),
        {'@type': 'FAQPage', 'inLanguage': lang, 'mainEntity': [
            {'@type': 'Question', 'name': text_only(q), 'acceptedAnswer': {'@type': 'Answer', 'text': text_only(a)}} for q, a in c['faq']]},
    ]}
    enquire = wa(t['wa'].format(name=c['name']))
    if is_pos:
        body = hardware_block(lang, root, t) + f'''
        <section class="section">
            <header class="sec-head reveal"><span class="num">// 02</span><div><h2>{t['pk_h']}</h2></div></header>
            <div class="sv-grid">{''.join(f'<div class="sv-card reveal"><h3>{a}</h3><p>{b}</p></div>' for a, b in c['packages'])}</div>
        </section>'''
    else:
        body = f'''
        <section class="section">
            <header class="sec-head reveal"><span class="num">// 01</span><div><h2>{t['offer']}</h2></div></header>
            <div class="sv-grid">{''.join(f'<div class="sv-card reveal"><span class="i">{i:02d}</span><h3>{a}</h3><p>{b}</p></div>' for i, (a, b) in enumerate(c['offer'], 1))}</div>
        </section>'''
    if slug == 'web-development':
        body += portfolio_block(lang, root, 'WORK')
    steps = ''.join(f'<li><span>{"Step" if lang == "en" else "الخطوة"} {i}</span><h3>{a}</h3><p>{b}</p></li>' for i, (a, b) in enumerate(t['steps'], 1))
    faq = ''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q, a in c['faq'])
    others = [x for x in ALL if x['slug'] != slug]
    links = ''.join(f'<a href="{x["slug"]}.html">{x[lang]["name"]} <span class="arr">&rarr;</span></a>' for x in others)
    region_note = t['areas_all'] if s['region'] == 'all' else t['areas_uae']
    return head(lang, root, slug, c['title'], c['description'], c['keywords'], image, ld) + f'''
<body class="pd-page">
{header(lang, root, switch_href, active='#services')}

    <main>
        <header class="bl-hero sv-hero">
            <nav class="crumbs" aria-label="Breadcrumb"><a href="../index.html">{t['home']}</a><span>/</span><a href="./">{t['services']}</a><span>/</span><b>{c['name']}</b></nav>
            <span class="tag">{t['services']}{' &middot; ' + s['num'] if s.get('num') else ''}</span>
            <h1>{c['h1']}</h1>
            <p class="lead">{c['lead']}</p>
            <p class="bl-meta">{region_note}</p>
            <div class="hero-actions">
                <a href="{enquire}" target="_blank" rel="noopener" class="btn btn-accent">{t['quote']} <span class="arr">&rarr;</span></a>
                <a href="tel:{PHONE}" class="btn btn-line">{PUI[lang]['call']}</a>
            </div>
            {related(s, lang, root, t)}
        </header>
{body}
        <section class="section">
            <header class="sec-head reveal"><span class="num">// 02</span><div><h2>{t['how']}</h2></div></header>
            <ol class="process reveal">{steps}</ol>
        </section>
{areas(s, t)}
        <section class="section">
            <header class="sec-head reveal"><span class="num">// 04</span><div><h2>{t['faq']}</h2></div></header>
            <div class="faq reveal">{faq}</div>
        </section>

        <section class="section">
            <div class="pd-cta hud reveal">
                <div><span class="tag">Anqah Tech</span><h2>{t['cta_h'].format(name=c['name'])}</h2><p>{t['cta_p']}</p></div>
                <div class="hero-actions">
                    <a href="{enquire}" target="_blank" rel="noopener" class="btn btn-accent">{t['quote']} <span class="arr">&rarr;</span></a>
                    <a href="../index.html#contact" class="btn btn-line">{PUI[lang]['form']}</a>
                </div>
            </div>
        </section>

        <section class="section">
            <header class="sec-head reveal"><span class="num">// 05</span><div><h2>{t['other']}</h2></div></header>
            <nav class="sv-links reveal">{links}</nav>
        </section>
    </main>
''' + tail(lang, root, switch_href)


def hub_page(lang):
    t = UI[lang]
    root = '../../' if lang == 'ar' else '../'
    u = url('', lang)
    home = f'{SITE}/{"ar/" if lang == "ar" else ""}'
    switch_href = '../../services/' if lang == 'ar' else '../ar/services/'
    ld = {'@context': 'https://schema.org', '@graph': [
        {'@type': 'CollectionPage', '@id': f'{u}#page', 'name': text_only(t['hub_h1']), 'url': u, 'inLanguage': lang,
         'description': text_only(t['hub_desc']), 'publisher': {'@id': f'{SITE}/#org'},
         'mainEntity': {'@type': 'ItemList', 'itemListElement': [
             {'@type': 'ListItem', 'position': i, 'url': url(s['slug'], lang), 'name': text_only(s[lang]['name'])} for i, s in enumerate(ALL, 1)]}},
        breadcrumbs(lang, [(t['home'], home), (t['services'], u)]),
    ]}
    cards = ''.join(
        f'<a class="sv-card sv-link reveal" href="{s["slug"]}.html"><span class="i">{s.get("num", "POS")}</span><h3>{s[lang]["name"]}</h3>'
        f'<p>{s[lang]["lead"]}</p><span class="link-btn">{"View service" if lang == "en" else "عرض الخدمة"} <span class="arr">&rarr;</span></span></a>'
        for s in ALL)
    kw = ', '.join(s[lang]['keywords'].split(', ')[0] for s in ALL)
    return head(lang, root, '', t['hub_title'], t['hub_desc'], kw, f'{SITE}/images/og/og-home.jpg', ld) + f'''
<body class="pd-page">
{header(lang, root, switch_href, active='#services')}

    <main>
        <header class="bl-hero">
            <nav class="crumbs" aria-label="Breadcrumb"><a href="../index.html">{t['home']}</a><span>/</span><b>{t['services']}</b></nav>
            <h1>{t['hub_h1']}</h1>
            <p class="lead">{t['hub_lead']}</p>
        </header>
        <section class="section bl-index">
            <div class="sv-grid sv-hub">{cards}</div>
        </section>
{portfolio_block(lang, root, 'WORK')}
    </main>
''' + tail(lang, root, switch_href)


def main():
    for lang, folder in (('en', ROOT / 'services'), ('ar', ROOT / 'ar' / 'services')):
        folder.mkdir(parents=True, exist_ok=True)
        files = {'index.html': hub_page(lang), **{f'{s["slug"]}.html': service_page(s, lang) for s in ALL}}
        for name, html in files.items():
            (folder / name).write_text(html, encoding='utf-8')
        print('wrote', len(files), 'pages in', folder.relative_to(ROOT).as_posix())


if __name__ == '__main__':
    main()
