"""Generates the Guides section in English and Arabic from tools/blog_content.py:
    blog/index.html, blog/<slug>.html, ar/blog/index.html, ar/blog/<slug>.html
Run:  python tools/build_blog.py   (then python tools/build_sitemap.py)
"""
import json
from html import escape, unescape

from blog_content import ARTICLES
from build_product_pages import (PRODUCTS, ROOT, SITE, UI, WA_ICON, WHATSAPP, footer, header, localize, text_only)

MONTHS_AR = ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر']
MONTHS_EN = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October',
             'November', 'December']
HREFLANG_EN = ('en', 'en-AE', 'en-SA', 'en-IN')
HREFLANG_AR = ('ar', 'ar-AE', 'ar-SA')


def blog_url(slug, lang):
    return f'{SITE}/{"ar/" if lang == "ar" else ""}blog/{slug + ".html" if slug else ""}'


def nice_date(iso, lang):
    y, m, d = (int(x) for x in iso.split('-'))
    return f'{d} {(MONTHS_AR if lang == "ar" else MONTHS_EN)[m - 1]} {y}'


def read_minutes(a):
    words = len(text_only(' '.join([a['intro']] + [h + ' ' + b for h, b in a['sections']])).split())
    return max(2, round(words / 200))


def product(slug, lang):
    return localize(next(p for p in PRODUCTS if p['slug'] == slug), lang)


def head(lang, root, title, desc, keywords, url, slug, image, ld, og_type):
    hreflang = '\n'.join(
        [f'    <link rel="alternate" hreflang="{h}" href="{blog_url(slug, "en")}">' for h in HREFLANG_EN] +
        [f'    <link rel="alternate" hreflang="{h}" href="{blog_url(slug, "ar")}">' for h in HREFLANG_AR] +
        [f'    <link rel="alternate" hreflang="x-default" href="{blog_url(slug, "en")}">'])
    fonts = ('family=Chakra+Petch:wght@500;600;700&family=IBM+Plex+Sans:wght@400;500;600'
             + ('&family=IBM+Plex+Sans+Arabic:wght@400;500;600;700&family=Noto+Kufi+Arabic:wght@600;700;800' if lang == 'ar' else '')
             + '&family=JetBrains+Mono:wght@400;500;700&display=swap')
    title, desc = escape(unescape(title)), escape(unescape(desc))
    return f'''<!DOCTYPE html>
<html lang="{lang}" dir="{'rtl' if lang == 'ar' else 'ltr'}">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Generated by tools/build_blog.py - edit tools/blog_content.py, not this file. -->
    <title>{title}</title>
    <meta name="description" content="{desc}">
    <meta name="keywords" content="{escape(keywords)}">
    <meta name="robots" content="index, follow, max-image-preview:large">
    <meta name="theme-color" content="#07080a">
    <link rel="canonical" href="{url}">
{hreflang}
    <meta name="geo.region" content="AE-AZ">
    <meta name="geo.placename" content="Abu Dhabi">
    <link rel="icon" href="{root}favicon.ico" sizes="48x48">
    <link rel="icon" type="image/png" sizes="48x48" href="{root}images/favicon-48.png">
    <link rel="icon" type="image/png" sizes="192x192" href="{root}images/favicon.png">
    <link rel="apple-touch-icon" href="{root}images/apple-touch-icon.png">
    <link rel="manifest" href="{root}site.webmanifest">
    <meta property="og:type" content="{og_type}">
    <meta property="og:site_name" content="Anqah Tech">
    <meta property="og:url" content="{url}">
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{desc}">
    <meta property="og:image" content="{image}">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta property="og:locale" content="{'ar_AE' if lang == 'ar' else 'en_AE'}">
    <meta property="og:locale:alternate" content="{'en_AE' if lang == 'ar' else 'ar_AE'}">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="{title}">
    <meta name="twitter:description" content="{desc}">
    <meta name="twitter:image" content="{image}">
    <script type="application/ld+json">
{json.dumps(ld, ensure_ascii=False, indent=2)}
    </script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?{fonts}" rel="stylesheet">
    <link rel="stylesheet" href="{root}style.css">
</head>
'''


def tail(lang, root, switch_href):
    return f'''
{footer(lang, root, switch_href, product_dir='../products/')}

    <a class="fab-pdf" href="{root}downloads/Anqah-Tech-Company-Profile{"-AR" if lang == "ar" else ""}.pdf" download aria-label="{UI[lang]['profile_dl']}" title="{UI[lang]['profile_dl']}">
        <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M12 11v6m0 0-3-3m3 3 3-3"/></svg>
    </a>
    <a class="fab-wa" href="https://wa.me/{WHATSAPP}" target="_blank" rel="noopener" aria-label="{UI[lang]['chat']}">
        {WA_ICON}
    </a>

    <script src="{root}script.js"></script>
</body>

</html>
'''


def card(a, lang, href):
    c = a[lang]
    return (f'<a class="bl-card hud" href="{href}"><small>{product(a["product"], lang)["name"]} &middot; '
            f'{UI[lang]["min"].format(n=read_minutes(c))}</small><h3>{c["title"]}</h3><p>{c["description"]}</p>'
            f'<span class="link-btn">{UI[lang]["read"]} <span class="arr">&rarr;</span></span></a>')


def breadcrumbs(lang, items):
    return {'@type': 'BreadcrumbList', 'itemListElement': [
        {'@type': 'ListItem', 'position': i, 'name': unescape(n), 'item': u} for i, (n, u) in enumerate(items, 1)]}


def article_page(a, lang):
    t, c = UI[lang], a[lang]
    root = '../../' if lang == 'ar' else '../'
    url = blog_url(a['slug'], lang)
    home = f'{SITE}/{"ar/" if lang == "ar" else ""}'
    p = product(a['product'], lang)
    image = f'{SITE}/images/og/{p["seo"]["og"]}'
    org = {'@type': 'Organization', '@id': f'{SITE}/#org', 'name': 'Anqah Tech', 'url': f'{SITE}/',
           'logo': f'{SITE}/images/logo-full-navy.png'}
    ld = {'@context': 'https://schema.org', '@graph': [
        {'@type': 'Article', '@id': f'{url}#article', 'headline': unescape(c['title']),
         'description': unescape(c['description']), 'inLanguage': lang, 'url': url, 'mainEntityOfPage': url,
         'image': image, 'datePublished': a['date'], 'dateModified': a['date'], 'author': org, 'publisher': org,
         'keywords': c['keywords'], 'about': {'@id': f'{SITE}/{"ar/" if lang == "ar" else ""}products/{a["product"]}.html#product'}},
        breadcrumbs(lang, [(t['home'], home), (t['guides'], blog_url('', lang)), (c['title'], url)]),
    ]}
    switch_href = f'../../blog/{a["slug"]}.html' if lang == 'ar' else f'../ar/blog/{a["slug"]}.html'
    body = ''.join(f'<h2>{h}</h2>{html}' for h, html in c['sections'])
    more = ''.join(card(o, lang, f'{o["slug"]}.html') for o in ARTICLES if o['slug'] != a['slug'])
    return head(lang, root, f'{c["title"]} | Anqah Tech', c['description'], c['keywords'], url, a['slug'], image, ld, 'article') + f'''
<body class="pd-page">
{header(lang, root, switch_href, active='../blog/')}

    <main>
        <article>
            <header class="bl-hero">
                <nav class="crumbs" aria-label="Breadcrumb"><a href="../index.html">{t['home']}</a><span>/</span><a href="./">{t['guides']}</a><span>/</span><b>{p['name']}</b></nav>
                <span class="tag">{p['category']}</span>
                <h1>{c['title']}</h1>
                <p class="bl-meta">{t['published']} <time datetime="{a['date']}">{nice_date(a['date'], lang)}</time> &middot; {t['min'].format(n=read_minutes(c))} &middot; Anqah Tech</p>
                <p class="lead">{c['intro']}</p>
            </header>
            <div class="bl-body">{body}</div>
        </article>

        <section class="section">
            <div class="pd-cta hud">
                <div>
                    <span class="tag">{t['related']}</span>
                    <h2>{p['name']}</h2>
                    <p>{c['cta']}</p>
                </div>
                <div class="hero-actions">
                    <a href="../products/{p['slug']}.html" class="btn btn-accent">{t['see'].format(name=p['name'])} <span class="arr">&rarr;</span></a>
                    <a href="../index.html#contact" class="btn btn-line">{t['form']}</a>
                </div>
            </div>
        </section>

        <section class="section">
            <header class="sec-head"><span class="num">// GUIDES</span><div><h2>{t['more_guides']}</h2></div></header>
            <div class="bl-grid">{more}</div>
        </section>
    </main>
''' + tail(lang, root, switch_href)


def index_page(lang):
    t = UI[lang]
    root = '../../' if lang == 'ar' else '../'
    url = blog_url('', lang)
    home = f'{SITE}/{"ar/" if lang == "ar" else ""}'
    image = f'{SITE}/images/og/og-home.jpg'
    ld = {'@context': 'https://schema.org', '@graph': [
        {'@type': 'CollectionPage', '@id': f'{url}#page', 'name': unescape(t['guides_h']), 'url': url,
         'inLanguage': lang, 'description': unescape(t['guides_p']), 'publisher': {'@id': f'{SITE}/#org'},
         'mainEntity': {'@type': 'ItemList', 'itemListElement': [
             {'@type': 'ListItem', 'position': i, 'url': blog_url(a['slug'], lang), 'name': unescape(a[lang]['title'])}
             for i, a in enumerate(ARTICLES, 1)]}},
        breadcrumbs(lang, [(t['home'], home), (t['guides'], url)]),
    ]}
    switch_href = '../../blog/' if lang == 'ar' else '../ar/blog/'
    cards = ''.join(card(a, lang, f'{a["slug"]}.html') for a in ARTICLES)
    kw = ', '.join(a[lang]['keywords'].split(', ')[0] for a in ARTICLES)
    return head(lang, root, t['guides_title'], t['guides_p'], kw, url, '', image, ld, 'website') + f'''
<body class="pd-page">
{header(lang, root, switch_href, active='../blog/')}

    <main>
        <header class="bl-hero">
            <nav class="crumbs" aria-label="Breadcrumb"><a href="../index.html">{t['home']}</a><span>/</span><b>{t['guides']}</b></nav>
            <h1>{t['guides_h']}</h1>
            <p class="lead">{t['guides_p']}</p>
        </header>
        <section class="section bl-index">
            <div class="bl-grid">{cards}</div>
        </section>
    </main>
''' + tail(lang, root, switch_href)


def main():
    for lang, folder in (('en', ROOT / 'blog'), ('ar', ROOT / 'ar' / 'blog')):
        folder.mkdir(parents=True, exist_ok=True)
        files = {'index.html': index_page(lang), **{f'{a["slug"]}.html': article_page(a, lang) for a in ARTICLES}}
        for name, html in files.items():
            (folder / name).write_text(html, encoding='utf-8')
            print('wrote', (folder / name).relative_to(ROOT).as_posix())


if __name__ == '__main__':
    main()
