"""Service landing pages (English + Arabic), rendered by tools/build_service_pages.py.

region: 'all' = UAE, Saudi Arabia & India (remote / software work); 'uae' = on-site installation work in the UAE.
Keep claims factual: describe what we do; no prices, brands, certifications or numbers we can't back up.
"""

SERVICES = [
    {
        'slug': 'web-development', 'region': 'all', 'num': '01', 'related': None,
        'en': {
            'name': 'Web Design &amp; Development',
            'title': 'Website Design &amp; Development Company in UAE, KSA &amp; India | Anqah Tech',
            'description': 'Website design and development in Abu Dhabi, Dubai, Riyadh and India: fast, mobile-friendly, SEO-ready business websites and web applications in English and Arabic.',
            'keywords': 'website development UAE, web design Abu Dhabi, web design Dubai, website company Riyadh, web development India, Arabic website design, web application development',
            'h1': 'Website design &amp; development',
            'lead': 'Fast, mobile-friendly websites and web applications that bring in enquiries &mdash; built for search engines from day one, in English, Arabic or both.',
            'offer': [
                ('Business websites', 'Company sites, landing pages and portfolios that load fast and look right on every phone.'),
                ('Web applications', 'Dashboards, portals and booking or ordering systems built around your workflow.'),
                ('Arabic &amp; bilingual sites', 'Right-to-left Arabic layouts with proper fonts, alongside English.'),
                ('SEO-ready build', 'Clean structure, structured data, sitemaps and page speed taken care of from the start.'),
                ('E-commerce', 'Online catalogues and shops with product pages, enquiries or online ordering.'),
                ('Hosting &amp; care', 'Domain, hosting, updates and backups, so the site keeps running.'),
            ],
            'faq': [
                ('Can you build a website in Arabic and English?', 'Yes. We build bilingual sites with a proper right-to-left Arabic layout, so both languages read naturally.'),
                ('Will my website work on mobile?', 'Yes. Every site we build is responsive and tested on phones, tablets and desktops.'),
                ('Do you help with SEO?', 'Yes. Sites are built search-ready, and we also offer ongoing SEO through our digital marketing service.'),
            ],
        },
        'ar': {
            'name': 'تصميم وتطوير المواقع',
            'title': 'شركة تصميم وتطوير مواقع في الإمارات والسعودية والهند | Anqah Tech',
            'description': 'تصميم وتطوير مواقع الإنترنت في أبوظبي ودبي والرياض والهند: مواقع وتطبيقات ويب سريعة ومتوافقة مع الجوال وجاهزة لمحركات البحث بالعربية والإنجليزية.',
            'keywords': 'تصميم مواقع الإمارات, تصميم مواقع أبوظبي, تصميم مواقع دبي, شركة تصميم مواقع الرياض, تطوير مواقع, تصميم موقع عربي, تطوير تطبيقات ويب',
            'h1': 'تصميم وتطوير المواقع',
            'lead': 'مواقع وتطبيقات ويب سريعة ومتوافقة مع الجوال تجلب لك الاستفسارات &mdash; مبنية لمحركات البحث من اليوم الأول، بالعربية أو الإنجليزية أو كليهما.',
            'offer': [
                ('مواقع الشركات', 'مواقع تعريفية وصفحات هبوط ومعارض أعمال سريعة التحميل وتظهر بشكل صحيح على كل جوال.'),
                ('تطبيقات الويب', 'لوحات تحكم وبوابات وأنظمة حجز أو طلب مصممة حول طريقة عملك.'),
                ('مواقع عربية وثنائية اللغة', 'تصميم عربي من اليمين إلى اليسار بخطوط مناسبة، إلى جانب الإنجليزية.'),
                ('بناء جاهز لمحركات البحث', 'هيكل نظيف وبيانات منظمة وخرائط موقع وسرعة صفحات من البداية.'),
                ('المتاجر الإلكترونية', 'كتالوجات ومتاجر إلكترونية مع صفحات منتجات واستفسارات أو طلب عبر الإنترنت.'),
                ('الاستضافة والرعاية', 'النطاق والاستضافة والتحديثات والنسخ الاحتياطي ليستمر عمل الموقع.'),
            ],
            'faq': [
                ('هل يمكنكم بناء موقع بالعربية والإنجليزية؟', 'نعم. نبني مواقع ثنائية اللغة بتصميم عربي صحيح من اليمين إلى اليسار، لتُقرأ اللغتان بشكل طبيعي.'),
                ('هل سيعمل موقعي على الجوال؟', 'نعم. كل موقع نبنيه متجاوب ومُختبر على الجوال والأجهزة اللوحية والحاسوب.'),
                ('هل تساعدون في تحسين محركات البحث؟', 'نعم. تُبنى المواقع جاهزة لمحركات البحث، ونقدّم أيضًا تحسينًا مستمرًا عبر خدمة التسويق الرقمي.'),
            ],
        },
    },
    {
        'slug': 'mobile-app-development', 'region': 'all', 'num': '02', 'related': 'sello-lite',
        'en': {
            'name': 'Mobile App Development',
            'title': 'Mobile App Development Company in UAE, KSA &amp; India | Anqah Tech',
            'description': 'Android and iOS app development in Abu Dhabi, Dubai, Riyadh and India: native and cross-platform apps with Flutter and React Native, including offline-first business apps.',
            'keywords': 'mobile app development UAE, app development Abu Dhabi, app developers Dubai, app development Saudi Arabia, Flutter developers, React Native app, Android app development India',
            'h1': 'Mobile app development',
            'lead': 'Android and iOS apps for businesses &mdash; from customer apps to offline-first tools your staff use every day. We build and ship our own apps, like SELLO Lite and the School Bell app.',
            'offer': [
                ('Android &amp; iOS apps', 'One codebase for both platforms with Flutter or React Native, or native where it matters.'),
                ('Offline-first apps', 'Apps that keep working without internet and sync or back up when they can.'),
                ('Business &amp; staff tools', 'Field service, ordering, inspections, attendance and other internal apps.'),
                ('IoT companion apps', 'Apps that control and monitor devices over WiFi, like our bell and tank apps.'),
                ('Arabic support', 'Right-to-left layouts and translations for Arabic-speaking users.'),
                ('Publishing &amp; updates', 'Store listings, releases and updates that never lose user data.'),
            ],
            'faq': [
                ('Do you build for both Android and iPhone?', 'Yes. We usually build one cross-platform app that runs on both, which keeps cost and maintenance down.'),
                ('Can the app work without internet?', 'Yes. We specialise in offline-first apps &mdash; SELLO Lite, for example, makes sales with no connection at all.'),
                ('Do you publish the app to the stores?', 'Yes. We prepare the listing and handle the release and later updates.'),
            ],
        },
        'ar': {
            'name': 'تطوير تطبيقات الجوال',
            'title': 'شركة تطوير تطبيقات جوال في الإمارات والسعودية والهند | Anqah Tech',
            'description': 'تطوير تطبيقات أندرويد و iOS في أبوظبي ودبي والرياض والهند: تطبيقات أصلية ومتعددة المنصات بـ Flutter و React Native، بما فيها تطبيقات أعمال تعمل دون إنترنت.',
            'keywords': 'تطوير تطبيقات الجوال الإمارات, تطوير تطبيقات أبوظبي, شركة برمجة تطبيقات دبي, تطوير تطبيقات السعودية, مطور تطبيقات Flutter, برمجة تطبيقات أندرويد',
            'h1': 'تطوير تطبيقات الجوال',
            'lead': 'تطبيقات أندرويد و iOS للأعمال &mdash; من تطبيقات العملاء إلى أدوات تعمل دون إنترنت يستخدمها موظفوك يوميًا. نبني وننشر تطبيقاتنا الخاصة مثل SELLO Lite وتطبيق جرس المدرسة.',
            'offer': [
                ('تطبيقات أندرويد و iOS', 'شيفرة واحدة للمنصتين بـ Flutter أو React Native، أو تطوير أصلي عند الحاجة.'),
                ('تطبيقات تعمل دون إنترنت', 'تطبيقات تستمر في العمل دون اتصال وتزامن أو تنسخ احتياطيًا عند توفره.'),
                ('أدوات الأعمال والموظفين', 'تطبيقات داخلية للخدمات الميدانية والطلبات والفحص والحضور وغيرها.'),
                ('تطبيقات لأجهزة إنترنت الأشياء', 'تطبيقات تتحكم بالأجهزة وتراقبها عبر WiFi، مثل تطبيقي الجرس والخزان.'),
                ('دعم العربية', 'تصميم من اليمين إلى اليسار وترجمات للمستخدمين الناطقين بالعربية.'),
                ('النشر والتحديثات', 'صفحات المتاجر والإصدارات والتحديثات دون فقدان بيانات المستخدمين.'),
            ],
            'faq': [
                ('هل تطوّرون لأندرويد وآيفون معًا؟', 'نعم. نبني عادةً تطبيقًا واحدًا متعدد المنصات يعمل على الاثنين، ما يخفض التكلفة والصيانة.'),
                ('هل يمكن أن يعمل التطبيق دون إنترنت؟', 'نعم. نتخصص في التطبيقات التي تعمل دون إنترنت &mdash; فمثلًا يُتم SELLO Lite المبيعات دون أي اتصال.'),
                ('هل تنشرون التطبيق في المتاجر؟', 'نعم. نجهّز صفحة التطبيق ونتولى النشر والتحديثات اللاحقة.'),
            ],
        },
    },
    {
        'slug': 'digital-marketing', 'region': 'all', 'num': '03', 'related': None,
        'en': {
            'name': 'Digital Marketing &amp; Branding',
            'title': 'Digital Marketing, SEO &amp; Branding in UAE, KSA &amp; India | Anqah Tech',
            'description': 'SEO, Google Business Profile, social media, PPC and brand identity for businesses in the UAE, Saudi Arabia and India &mdash; in English and Arabic.',
            'keywords': 'digital marketing UAE, SEO company Abu Dhabi, SEO Dubai, social media marketing UAE, Google ads UAE, branding agency Abu Dhabi, Arabic SEO, digital marketing Saudi Arabia',
            'h1': 'Digital marketing &amp; branding',
            'lead': 'Get found by the customers already searching for you &mdash; with SEO, Google Business Profile, social media and ads, in English and Arabic.',
            'offer': [
                ('Search engine optimisation', 'Technical SEO, content and local SEO so you rank for the searches that bring customers.'),
                ('Google Business Profile', 'Set-up and upkeep of your Maps listing, posts, photos and review replies.'),
                ('Social media', 'Content and management for Instagram, Facebook, LinkedIn and more.'),
                ('Pay-per-click ads', 'Google and social ad campaigns aimed at enquiries, not just clicks.'),
                ('Brand identity', 'Logo, colours, typography and brand guidelines that work in English and Arabic.'),
                ('Arabic SEO', 'Arabic keywords and pages for customers in the UAE and Saudi Arabia.'),
            ],
            'faq': [
                ('How long does SEO take to show results?', 'Usually a few weeks for new pages to be indexed and a few months for rankings to build; we report progress from Search Console.'),
                ('Do you do Arabic SEO?', 'Yes. We research Arabic search terms and build Arabic pages with proper hreflang so each language ranks.'),
                ('Can you manage our Google Business Profile?', 'Yes &mdash; set-up, categories, photos, posts and replying to reviews.'),
            ],
        },
        'ar': {
            'name': 'التسويق الرقمي والهوية التجارية',
            'title': 'التسويق الرقمي وتحسين محركات البحث والهوية في الإمارات والسعودية | Anqah Tech',
            'description': 'تحسين محركات البحث وملف النشاط التجاري على Google ووسائل التواصل والإعلانات المدفوعة والهوية التجارية للأعمال في الإمارات والسعودية والهند &mdash; بالعربية والإنجليزية.',
            'keywords': 'التسويق الرقمي الإمارات, شركة سيو أبوظبي, تحسين محركات البحث دبي, التسويق عبر وسائل التواصل, إعلانات جوجل الإمارات, تصميم هوية تجارية, سيو عربي, التسويق الرقمي السعودية',
            'h1': 'التسويق الرقمي والهوية التجارية',
            'lead': 'كن في متناول العملاء الذين يبحثون عنك بالفعل &mdash; بتحسين محركات البحث وملف النشاط على Google ووسائل التواصل والإعلانات، بالعربية والإنجليزية.',
            'offer': [
                ('تحسين محركات البحث', 'تحسين تقني ومحتوى وسيو محلي لتظهر في عمليات البحث التي تجلب العملاء.'),
                ('ملف النشاط التجاري على Google', 'إعداد قائمتك على الخرائط وتحديثها بالمنشورات والصور والرد على التقييمات.'),
                ('وسائل التواصل الاجتماعي', 'محتوى وإدارة لحسابات إنستغرام وفيسبوك ولينكدإن وغيرها.'),
                ('الإعلانات المدفوعة', 'حملات إعلانية على Google ووسائل التواصل تستهدف الاستفسارات لا النقرات فقط.'),
                ('الهوية التجارية', 'شعار وألوان وخطوط ودليل هوية يعمل بالعربية والإنجليزية.'),
                ('سيو عربي', 'كلمات بحث وصفحات عربية للعملاء في الإمارات والسعودية.'),
            ],
            'faq': [
                ('متى تظهر نتائج تحسين محركات البحث؟', 'عادةً خلال أسابيع لفهرسة الصفحات الجديدة وبضعة أشهر لبناء الترتيب؛ ونقدّم تقارير التقدم من Search Console.'),
                ('هل تقدّمون سيو باللغة العربية؟', 'نعم. نبحث عن كلمات البحث العربية ونبني صفحات عربية مع إعدادات اللغة الصحيحة ليظهر كل إصدار.'),
                ('هل يمكنكم إدارة ملف نشاطنا على Google؟', 'نعم &mdash; الإعداد والفئات والصور والمنشورات والرد على التقييمات.'),
            ],
        },
    },
    {
        'slug': 'pos-systems', 'region': 'all', 'num': '04', 'related': 'sello',
        'en': {
            'name': 'POS Systems &amp; Business Solutions',
            'title': 'POS Systems for Retail &amp; Restaurants in UAE, KSA &amp; India | Anqah Tech',
            'description': 'Complete POS systems for supermarkets, shops, restaurants and cafés in the UAE, Saudi Arabia and India: SELLO software, POS machines, VAT/GST setup, installation and support.',
            'keywords': 'POS system UAE, POS system Abu Dhabi, POS system Dubai, restaurant POS UAE, retail POS system, POS system Saudi Arabia, billing software India, cashier system, ERP for retail',
            'h1': 'POS systems &amp; business solutions',
            'lead': 'Complete point-of-sale systems for retail stores, supermarkets, restaurants and caf&eacute;s &mdash; our own SELLO software with the POS hardware, set up for your taxes and supported locally.',
            'offer': [
                ('Retail POS', 'Barcode billing, stock, purchasing, suppliers and customer credit for shops and supermarkets.'),
                ('Restaurant &amp; caf&eacute; POS', 'Tables, kitchen display, modifiers, portions and bill splitting.'),
                ('POS hardware', 'Touch terminals, tablets, receipt printers, cash drawers and kitchen screens.'),
                ('VAT &amp; GST setup', 'Tax rates, tax-inclusive pricing and tax reports set up for your country.'),
                ('Offline billing', 'SELLO runs on your shop network, so billing keeps going when the internet drops.'),
                ('Training &amp; support', 'Staff training at go-live and ongoing support and AMC.'),
            ],
            'faq': [
                ('Which POS software do you install?', 'Our own SELLO POS for shops and restaurants, and SELLO Lite, an offline POS app for Android phones and tablets.'),
                ('Do you supply the POS machines too?', 'Yes. We supply complete POS systems &mdash; hardware and software from one supplier, installed and supported.'),
                ('Does it work without internet?', 'Yes. SELLO runs on your own shop network, so billing, stock and reports keep working offline.'),
            ],
        },
        'ar': {
            'name': 'أنظمة نقاط البيع وحلول الأعمال',
            'title': 'أنظمة نقاط البيع (كاشير) للمحلات والمطاعم في الإمارات والسعودية | Anqah Tech',
            'description': 'أنظمة نقاط بيع متكاملة للسوبرماركت والمحلات والمطاعم والمقاهي في الإمارات والسعودية والهند: برنامج SELLO وأجهزة الكاشير وإعداد الضريبة والتركيب والدعم.',
            'keywords': 'نظام نقاط البيع الإمارات, نظام كاشير أبوظبي, نظام كاشير دبي, نظام نقاط بيع للمطاعم, برنامج كاشير السعودية, برنامج كاشير للمحلات, نظام كاشير متكامل',
            'h1': 'أنظمة نقاط البيع وحلول الأعمال',
            'lead': 'أنظمة نقاط بيع متكاملة لمتاجر التجزئة والسوبرماركت والمطاعم والمقاهي &mdash; برنامجنا SELLO مع أجهزة الكاشير، مُعدّ لضرائبك ومدعوم محليًا.',
            'offer': [
                ('كاشير التجزئة', 'فوترة بالباركود ومخزون ومشتريات وموردون وحسابات آجلة للمحلات والسوبرماركت.'),
                ('كاشير المطاعم والمقاهي', 'الطاولات وشاشة المطبخ والإضافات والأحجام وتقسيم الفاتورة.'),
                ('أجهزة نقاط البيع', 'أجهزة لمس وأجهزة لوحية وطابعات إيصالات وأدراج نقود وشاشات مطبخ.'),
                ('إعداد ضريبة القيمة المضافة', 'نسب الضريبة والأسعار الشاملة للضريبة وتقارير الضريبة لبلدك.'),
                ('فوترة دون إنترنت', 'يعمل SELLO على شبكة متجرك، فتستمر الفوترة عند انقطاع الإنترنت.'),
                ('التدريب والدعم', 'تدريب الموظفين عند التشغيل ودعم مستمر وعقود صيانة.'),
            ],
            'faq': [
                ('ما برنامج نقاط البيع الذي تثبّتونه؟', 'برنامجنا SELLO للمحلات والمطاعم، و SELLO Lite تطبيق كاشير يعمل دون إنترنت على هواتف وأجهزة أندرويد اللوحية.'),
                ('هل توفّرون أجهزة الكاشير أيضًا؟', 'نعم. نوفّر أنظمة نقاط بيع متكاملة &mdash; الأجهزة والبرنامج من مورّد واحد مع التركيب والدعم.'),
                ('هل يعمل دون إنترنت؟', 'نعم. يعمل SELLO على شبكة متجرك، فتستمر الفوترة والمخزون والتقارير دون اتصال.'),
            ],
        },
    },
    {
        'slug': 'it-solutions', 'region': 'uae', 'num': '05', 'related': None,
        'en': {
            'name': 'IT Solutions &amp; Infrastructure',
            'title': 'IT Solutions &amp; IT Support in Abu Dhabi, Dubai &amp; UAE | Anqah Tech',
            'description': 'IT infrastructure and support for businesses in Abu Dhabi, Dubai and across the UAE: office IT setup, servers, networking, backups, cloud and ongoing support.',
            'keywords': 'IT solutions Abu Dhabi, IT support Dubai, IT company UAE, server setup Abu Dhabi, office IT setup UAE, network infrastructure UAE, IT services Abu Dhabi',
            'h1': 'IT solutions &amp; infrastructure',
            'lead': 'Office IT that just works &mdash; computers, servers, networks, backups and cloud, set up properly and supported by one local team.',
            'offer': [
                ('Office IT setup', 'Computers, printers, user accounts and email for new and growing offices.'),
                ('Servers &amp; storage', 'File and application servers, NAS storage and access control.'),
                ('Networking', 'Routers, switches, firewalls and VLANs designed for your premises.'),
                ('Backup &amp; recovery', 'Scheduled backups and a tested plan to restore when something fails.'),
                ('Cloud services', 'Email, file sharing and cloud hosting set up and secured.'),
                ('IT support', 'On-site and remote support, plus annual maintenance contracts.'),
            ],
            'faq': [
                ('Do you support small offices?', 'Yes. We support offices of every size, from a few users to multi-floor sites.'),
                ('Can you take over our existing IT?', 'Yes. We start with a review of what you have, then fix, document and maintain it.'),
                ('Do you offer maintenance contracts?', 'Yes. Our AMC covers preventive maintenance and on-site support for your IT.'),
            ],
        },
        'ar': {
            'name': 'حلول وبنية تحتية لتقنية المعلومات',
            'title': 'حلول ودعم تقنية المعلومات في أبوظبي ودبي والإمارات | Anqah Tech',
            'description': 'بنية تحتية ودعم لتقنية المعلومات للشركات في أبوظبي ودبي وجميع الإمارات: تجهيز المكاتب والخوادم والشبكات والنسخ الاحتياطي والحلول السحابية والدعم المستمر.',
            'keywords': 'حلول تقنية المعلومات أبوظبي, دعم فني دبي, شركة تقنية معلومات الإمارات, تجهيز خوادم أبوظبي, تجهيز مكاتب تقنية, بنية تحتية للشبكات الإمارات',
            'h1': 'حلول وبنية تحتية لتقنية المعلومات',
            'lead': 'تقنية معلومات للمكاتب تعمل ببساطة &mdash; حواسيب وخوادم وشبكات ونسخ احتياطي وسحابة، مُعدّة بشكل صحيح ومدعومة من فريق محلي واحد.',
            'offer': [
                ('تجهيز المكاتب', 'الحواسيب والطابعات وحسابات المستخدمين والبريد للمكاتب الجديدة والمتنامية.'),
                ('الخوادم والتخزين', 'خوادم الملفات والتطبيقات وأجهزة التخزين الشبكي وصلاحيات الوصول.'),
                ('الشبكات', 'موجّهات ومحوّلات وجدران حماية وشبكات افتراضية مصممة لموقعك.'),
                ('النسخ الاحتياطي والاستعادة', 'نسخ احتياطي مجدول وخطة استعادة مُختبرة عند حدوث عطل.'),
                ('الخدمات السحابية', 'إعداد البريد ومشاركة الملفات والاستضافة السحابية وتأمينها.'),
                ('الدعم الفني', 'دعم في الموقع وعن بُعد، مع عقود صيانة سنوية.'),
            ],
            'faq': [
                ('هل تدعمون المكاتب الصغيرة؟', 'نعم. ندعم المكاتب بجميع أحجامها، من بضعة مستخدمين إلى مواقع متعددة الطوابق.'),
                ('هل يمكنكم تولّي أنظمتنا الحالية؟', 'نعم. نبدأ بمراجعة ما لديك، ثم نصلحه ونوثّقه ونصونه.'),
                ('هل تقدّمون عقود صيانة؟', 'نعم. تشمل عقود الصيانة السنوية الصيانة الوقائية والدعم في الموقع.'),
            ],
        },
    },
    {
        'slug': 'cctv-installation', 'region': 'uae', 'num': '06', 'related': None,
        'en': {
            'name': 'CCTV Installation &amp; Service',
            'title': 'CCTV Installation in Abu Dhabi, Dubai &amp; UAE | Anqah Tech',
            'description': 'CCTV camera installation, upgrades and maintenance for homes, villas, shops, offices and warehouses in Abu Dhabi, Dubai and across the UAE, with remote viewing on your phone.',
            'keywords': 'CCTV installation Abu Dhabi, CCTV installation Dubai, CCTV company UAE, security camera installation, IP camera installation UAE, CCTV for villa, CCTV maintenance Abu Dhabi',
            'h1': 'CCTV installation &amp; service',
            'lead': 'Security camera systems for homes, villas, shops, offices and warehouses &mdash; designed for your site, installed neatly and viewable from your phone.',
            'offer': [
                ('Site survey &amp; design', 'Camera positions, coverage and recording time planned around your premises.'),
                ('HD, 4K &amp; IP cameras', 'Indoor and outdoor cameras, including night vision.'),
                ('NVR / DVR recording', 'Recorders sized for the days of footage you need to keep.'),
                ('Remote viewing', 'Live and recorded video on your phone, wherever you are.'),
                ('Upgrades &amp; repairs', 'Replace old analogue systems or fix cameras that have stopped working.'),
                ('Maintenance', 'Regular checks and cleaning under an annual maintenance contract.'),
            ],
            'faq': [
                ('Can I watch the cameras on my phone?', 'Yes. We set up remote viewing so you can see live and recorded footage from your phone.'),
                ('Do you install CCTV for villas and homes?', 'Yes &mdash; for villas and homes as well as shops, offices and warehouses.'),
                ('Can you upgrade our old CCTV system?', 'Yes. We can reuse what still works and replace what doesn&rsquo;t, or move you to IP cameras.'),
            ],
        },
        'ar': {
            'name': 'تركيب وصيانة كاميرات المراقبة',
            'title': 'تركيب كاميرات مراقبة في أبوظبي ودبي والإمارات | Anqah Tech',
            'description': 'تركيب وتحديث وصيانة كاميرات المراقبة للمنازل والفلل والمحلات والمكاتب والمستودعات في أبوظبي ودبي وجميع الإمارات، مع المشاهدة عن بُعد على جوالك.',
            'keywords': 'تركيب كاميرات مراقبة أبوظبي, تركيب كاميرات مراقبة دبي, شركة كاميرات مراقبة الإمارات, كاميرات IP, كاميرات مراقبة للفلل, صيانة كاميرات المراقبة',
            'h1': 'تركيب وصيانة كاميرات المراقبة',
            'lead': 'أنظمة كاميرات مراقبة للمنازل والفلل والمحلات والمكاتب والمستودعات &mdash; مصممة لموقعك، ومركّبة بإتقان، ويمكن مشاهدتها من جوالك.',
            'offer': [
                ('معاينة الموقع والتصميم', 'تخطيط مواقع الكاميرات والتغطية ومدة التسجيل حسب موقعك.'),
                ('كاميرات HD و 4K و IP', 'كاميرات داخلية وخارجية، بما فيها الرؤية الليلية.'),
                ('أجهزة تسجيل NVR / DVR', 'أجهزة تسجيل بسعة تناسب عدد أيام التسجيل التي تحتاجها.'),
                ('المشاهدة عن بُعد', 'بث مباشر وتسجيلات على جوالك أينما كنت.'),
                ('التحديث والإصلاح', 'استبدال الأنظمة التناظرية القديمة أو إصلاح الكاميرات المتوقفة.'),
                ('الصيانة', 'فحص وتنظيف دوري ضمن عقد صيانة سنوي.'),
            ],
            'faq': [
                ('هل يمكنني مشاهدة الكاميرات على جوالي؟', 'نعم. نُعدّ المشاهدة عن بُعد لتشاهد البث المباشر والتسجيلات من جوالك.'),
                ('هل تركّبون كاميرات للفلل والمنازل؟', 'نعم &mdash; للفلل والمنازل وكذلك المحلات والمكاتب والمستودعات.'),
                ('هل يمكنكم تحديث نظام الكاميرات القديم؟', 'نعم. نعيد استخدام ما يعمل ونستبدل ما لا يعمل، أو ننقلك إلى كاميرات IP.'),
            ],
        },
    },
    {
        'slug': 'access-control', 'region': 'uae', 'num': '07', 'related': None,
        'en': {
            'name': 'Access Control &amp; Time Attendance',
            'title': 'Access Control &amp; Time Attendance Systems in Abu Dhabi &amp; UAE | Anqah Tech',
            'description': 'Biometric and card access control, time attendance machines and intercom systems for offices, schools, warehouses and buildings in Abu Dhabi, Dubai and the UAE.',
            'keywords': 'access control system Abu Dhabi, access control Dubai, time attendance system UAE, biometric attendance machine, fingerprint attendance UAE, door access control, intercom installation UAE',
            'h1': 'Access control &amp; time attendance',
            'lead': 'Control who gets in and keep accurate attendance records &mdash; with fingerprint, face or card readers, door locks and intercoms, installed and set up for your staff.',
            'offer': [
                ('Biometric access', 'Fingerprint and face readers for offices, server rooms and stores.'),
                ('Card &amp; PIN access', 'Card, tag and keypad readers with electric locks and exit buttons.'),
                ('Time attendance', 'Attendance machines with reports for working hours, late arrivals and absences.'),
                ('Intercom &amp; video door phones', 'Audio and video intercoms for villas, buildings and offices.'),
                ('User management', 'Add and remove staff, set access times and see entry logs.'),
                ('Maintenance', 'Support and annual maintenance for readers, locks and controllers.'),
            ],
            'faq': [
                ('Can attendance reports be exported?', 'Yes. Attendance data can be exported for payroll and HR, typically to Excel.'),
                ('Can we limit access by time or door?', 'Yes. Each user can be allowed through specific doors at specific times.'),
                ('Do you install intercoms for villas?', 'Yes &mdash; audio and video intercoms for villas, buildings and offices.'),
            ],
        },
        'ar': {
            'name': 'التحكم بالدخول والحضور والانصراف',
            'title': 'أنظمة التحكم بالدخول والحضور والانصراف في أبوظبي والإمارات | Anqah Tech',
            'description': 'أنظمة دخول بالبصمة والبطاقة وأجهزة حضور وانصراف وأنظمة إنتركم للمكاتب والمدارس والمستودعات والمباني في أبوظبي ودبي والإمارات.',
            'keywords': 'نظام التحكم بالدخول أبوظبي, نظام دخول دبي, نظام حضور وانصراف الإمارات, جهاز بصمة حضور, بصمة الموظفين, أقفال الأبواب الإلكترونية, تركيب إنتركم',
            'h1': 'التحكم بالدخول والحضور والانصراف',
            'lead': 'تحكّم بمن يدخل واحتفظ بسجلات حضور دقيقة &mdash; بقارئات البصمة أو الوجه أو البطاقة وأقفال الأبواب والإنتركم، مركّبة ومُعدّة لموظفيك.',
            'offer': [
                ('الدخول بالبصمة', 'قارئات بصمة الإصبع والوجه للمكاتب وغرف الخوادم والمخازن.'),
                ('الدخول بالبطاقة والرمز', 'قارئات بطاقات ولوحات أرقام مع أقفال كهربائية وأزرار خروج.'),
                ('الحضور والانصراف', 'أجهزة حضور مع تقارير لساعات العمل والتأخير والغياب.'),
                ('الإنتركم وجرس الباب المرئي', 'إنتركم صوتي ومرئي للفلل والمباني والمكاتب.'),
                ('إدارة المستخدمين', 'إضافة الموظفين وحذفهم وتحديد أوقات الدخول ومراجعة سجلات الدخول.'),
                ('الصيانة', 'دعم وصيانة سنوية للقارئات والأقفال ووحدات التحكم.'),
            ],
            'faq': [
                ('هل يمكن تصدير تقارير الحضور؟', 'نعم. يمكن تصدير بيانات الحضور للرواتب والموارد البشرية، عادةً إلى Excel.'),
                ('هل يمكن تقييد الدخول حسب الوقت أو الباب؟', 'نعم. يمكن السماح لكل مستخدم بالدخول من أبواب محددة في أوقات محددة.'),
                ('هل تركّبون الإنتركم للفلل؟', 'نعم &mdash; إنتركم صوتي ومرئي للفلل والمباني والمكاتب.'),
            ],
        },
    },
    {
        'slug': 'network-solutions', 'region': 'uae', 'num': '08', 'related': None,
        'en': {
            'name': 'WiFi, GSM &amp; Network Solutions',
            'title': 'WiFi, Network Cabling &amp; GSM Signal Solutions in Abu Dhabi &amp; UAE | Anqah Tech',
            'description': 'Office and villa WiFi, structured network cabling, fibre and GSM mobile signal solutions in Abu Dhabi, Dubai and across the UAE.',
            'keywords': 'WiFi installation Abu Dhabi, network cabling Dubai, structured cabling UAE, villa WiFi coverage, mesh WiFi installation, GSM signal booster UAE, network installation Abu Dhabi',
            'h1': 'WiFi, GSM &amp; network solutions',
            'lead': 'Strong WiFi in every room, reliable cabling behind it and mobile signal where you need it &mdash; for offices, villas, warehouses and schools.',
            'offer': [
                ('WiFi coverage', 'Access points and mesh systems planned for full coverage, including large villas.'),
                ('Structured cabling', 'Cat6 and fibre cabling, patch panels and racks, neatly labelled.'),
                ('Network setup', 'Routers, switches, guest networks and firewalls configured and secured.'),
                ('GSM signal solutions', 'Improve weak mobile signal inside buildings and basements.'),
                ('Network troubleshooting', 'Find and fix slow, dropping or dead-zone connections.'),
                ('Maintenance', 'Ongoing support and annual maintenance for your network.'),
            ],
            'faq': [
                ('Can you fix weak WiFi in a large villa?', 'Yes. We plan access points or a mesh system around the layout so every room is covered.'),
                ('Do you do network cabling for new offices?', 'Yes &mdash; structured Cat6 and fibre cabling, racks and patch panels for new fit-outs.'),
                ('Can you improve mobile signal indoors?', 'Yes. We offer GSM signal solutions for buildings and basements with weak reception.'),
            ],
        },
        'ar': {
            'name': 'حلول WiFi وGSM والشبكات',
            'title': 'تركيب الواي فاي وتمديد الشبكات وتقوية إشارة الجوال في أبوظبي والإمارات | Anqah Tech',
            'description': 'شبكات واي فاي للمكاتب والفلل وتمديدات شبكات منظمة وألياف ضوئية وحلول تقوية إشارة الجوال في أبوظبي ودبي وجميع الإمارات.',
            'keywords': 'تركيب واي فاي أبوظبي, تمديد شبكات دبي, تمديدات شبكات الإمارات, تغطية واي فاي للفلل, تقوية إشارة الجوال الإمارات, تركيب شبكات أبوظبي',
            'h1': 'حلول WiFi وGSM والشبكات',
            'lead': 'واي فاي قوي في كل غرفة وتمديدات موثوقة خلفه وإشارة جوال حيث تحتاجها &mdash; للمكاتب والفلل والمستودعات والمدارس.',
            'offer': [
                ('تغطية الواي فاي', 'نقاط وصول وأنظمة شبكية مخططة لتغطية كاملة، بما فيها الفلل الكبيرة.'),
                ('التمديدات المنظمة', 'تمديدات Cat6 وألياف ضوئية ولوحات توصيل وخزائن، مع ترقيم مرتب.'),
                ('إعداد الشبكات', 'إعداد وتأمين الموجّهات والمحوّلات وشبكات الضيوف وجدران الحماية.'),
                ('تقوية إشارة الجوال', 'تحسين إشارة الجوال الضعيفة داخل المباني والسراديب.'),
                ('حل مشكلات الشبكة', 'اكتشاف الاتصالات البطيئة أو المنقطعة أو المناطق الميتة وإصلاحها.'),
                ('الصيانة', 'دعم مستمر وصيانة سنوية لشبكتك.'),
            ],
            'faq': [
                ('هل يمكنكم حل ضعف الواي فاي في فيلا كبيرة؟', 'نعم. نخطط نقاط الوصول أو نظامًا شبكيًا حسب التصميم لتغطية كل الغرف.'),
                ('هل تنفّذون تمديدات الشبكات للمكاتب الجديدة؟', 'نعم &mdash; تمديدات Cat6 وألياف ضوئية وخزائن ولوحات توصيل للتجهيزات الجديدة.'),
                ('هل يمكنكم تحسين إشارة الجوال داخل المبنى؟', 'نعم. نقدّم حلول تقوية إشارة الجوال للمباني والسراديب ضعيفة الاستقبال.'),
            ],
        },
    },
    {
        'slug': 'home-automation', 'region': 'uae', 'num': '09', 'related': 'water-monitoring',
        'en': {
            'name': 'Home, Gate &amp; AC Automation',
            'title': 'Smart Home, Gate &amp; AC Automation in Abu Dhabi, Dubai &amp; UAE | Anqah Tech',
            'description': 'Smart home automation for villas and apartments in Abu Dhabi, Dubai and the UAE: automatic gates, AC control, smart lighting, sensors and water tank monitoring, controlled from your phone.',
            'keywords': 'home automation Abu Dhabi, smart home Dubai, villa automation UAE, automatic gate installation Abu Dhabi, AC automation, smart lighting UAE, IoT home automation',
            'h1': 'Home, gate &amp; AC automation',
            'lead': 'Control your villa from your phone &mdash; gates, air conditioning, lights and sensors, plus water tank monitoring that warns you before the tank runs dry or overflows.',
            'offer': [
                ('Automatic gates', 'Sliding and swing gate motors with remote and phone control.'),
                ('AC control', 'Schedule and switch air conditioning from your phone to save energy.'),
                ('Smart lighting', 'Lights on schedules, scenes and sensors, controlled from the app.'),
                ('Sensors &amp; alerts', 'Motion, door and leak sensors that notify you when something happens.'),
                ('Water tank monitoring', 'Live tank level on your phone with Telegram alerts &mdash; our own product.'),
                ('Custom IoT', 'Bespoke automation built on the same devices we use for our own products.'),
            ],
            'faq': [
                ('Can I control everything from my phone?', 'Yes. Gates, AC, lights and sensors can be controlled and monitored from your phone.'),
                ('Can you automate an existing villa?', 'Yes. Most automation can be added to existing homes without major rewiring.'),
                ('Do you install automatic gates?', 'Yes &mdash; gate motors for sliding and swing gates, with remote and phone control.'),
            ],
        },
        'ar': {
            'name': 'أتمتة المنازل والبوابات والتكييف',
            'title': 'المنزل الذكي وأتمتة البوابات والتكييف في أبوظبي ودبي والإمارات | Anqah Tech',
            'description': 'أتمتة المنازل الذكية للفلل والشقق في أبوظبي ودبي والإمارات: بوابات آلية والتحكم بالتكييف وإضاءة ذكية وحساسات ومراقبة خزانات المياه، كلها من جوالك.',
            'keywords': 'أتمتة المنازل أبوظبي, المنزل الذكي دبي, أتمتة الفلل الإمارات, تركيب بوابات أوتوماتيك أبوظبي, التحكم بالتكييف, إضاءة ذكية, إنترنت الأشياء للمنازل',
            'h1': 'أتمتة المنازل والبوابات والتكييف',
            'lead': 'تحكّم بفيلتك من جوالك &mdash; البوابات والتكييف والإضاءة والحساسات، مع مراقبة خزان المياه التي تنبّهك قبل أن يفرغ أو يفيض.',
            'offer': [
                ('البوابات الآلية', 'محركات للبوابات المنزلقة والمتأرجحة مع التحكم بالريموت والجوال.'),
                ('التحكم بالتكييف', 'جدولة التكييف وتشغيله من جوالك لتوفير الطاقة.'),
                ('الإضاءة الذكية', 'إضاءة بجداول ومشاهد وحساسات، يتحكم بها التطبيق.'),
                ('الحساسات والتنبيهات', 'حساسات حركة وأبواب وتسرّب تنبّهك عند حدوث أي شيء.'),
                ('مراقبة خزان المياه', 'منسوب الخزان مباشرة على جوالك مع تنبيهات تيليجرام &mdash; من منتجاتنا.'),
                ('أتمتة مخصصة', 'أتمتة حسب الطلب مبنية على الأجهزة نفسها التي نستخدمها في منتجاتنا.'),
            ],
            'faq': [
                ('هل يمكنني التحكم بكل شيء من جوالي؟', 'نعم. يمكن التحكم بالبوابات والتكييف والإضاءة والحساسات ومراقبتها من جوالك.'),
                ('هل يمكنكم أتمتة فيلا قائمة؟', 'نعم. يمكن إضافة معظم الأتمتة إلى المنازل القائمة دون إعادة تمديد كبيرة.'),
                ('هل تركّبون البوابات الآلية؟', 'نعم &mdash; محركات للبوابات المنزلقة والمتأرجحة مع التحكم بالريموت والجوال.'),
            ],
        },
    },
    {
        'slug': 'automobile-solutions', 'region': 'uae', 'num': '10', 'related': None,
        'en': {
            'name': 'Automobile Solutions',
            'title': 'GPS Tracking, Dash Cams &amp; Fleet Solutions in Abu Dhabi &amp; UAE | Anqah Tech',
            'description': 'GPS vehicle tracking, dash cameras and fleet technology for companies and personal vehicles in Abu Dhabi, Dubai and across the UAE.',
            'keywords': 'GPS tracking Abu Dhabi, vehicle tracking UAE, fleet tracking Dubai, dash cam installation Abu Dhabi, fleet management UAE, car GPS tracker UAE',
            'h1': 'Automobile solutions',
            'lead': 'Know where your vehicles are and what happened on the road &mdash; GPS tracking, dash cameras and fleet technology, installed and supported.',
            'offer': [
                ('GPS tracking', 'Live vehicle location and trip history on your phone or computer.'),
                ('Dash cameras', 'Front and rear cameras that record what happens on the road.'),
                ('Fleet management', 'Trips, routes and driver reports for company vehicles.'),
                ('Alerts', 'Notifications for things like overspeeding or a vehicle leaving an area.'),
                ('Professional installation', 'Neat, hidden wiring by our technicians.'),
                ('Support', 'Help with apps, accounts and devices after installation.'),
            ],
            'faq': [
                ('Can I track my vehicles from my phone?', 'Yes. GPS tracking shows live location and trip history on your phone or computer.'),
                ('Do you install dash cams?', 'Yes &mdash; front and rear dash cameras, with tidy hidden wiring.'),
                ('Is this for companies or personal cars?', 'Both. We fit single personal vehicles as well as company fleets.'),
            ],
        },
        'ar': {
            'name': 'حلول المركبات',
            'title': 'تتبّع GPS وكاميرات السيارات وإدارة الأساطيل في أبوظبي والإمارات | Anqah Tech',
            'description': 'تتبّع المركبات بنظام GPS وكاميرات السيارات وتقنيات الأساطيل للشركات والسيارات الخاصة في أبوظبي ودبي وجميع الإمارات.',
            'keywords': 'تتبع GPS أبوظبي, تتبع المركبات الإمارات, تتبع الأساطيل دبي, تركيب كاميرا سيارة أبوظبي, إدارة الأساطيل الإمارات, جهاز تتبع سيارة',
            'h1': 'حلول المركبات',
            'lead': 'اعرف مكان مركباتك وما حدث على الطريق &mdash; تتبّع GPS وكاميرات السيارات وتقنيات الأساطيل، مع التركيب والدعم.',
            'offer': [
                ('تتبّع GPS', 'موقع المركبة مباشرة وسجل الرحلات على جوالك أو حاسوبك.'),
                ('كاميرات السيارات', 'كاميرات أمامية وخلفية تسجّل ما يحدث على الطريق.'),
                ('إدارة الأساطيل', 'تقارير الرحلات والمسارات والسائقين لمركبات الشركة.'),
                ('التنبيهات', 'إشعارات مثل تجاوز السرعة أو خروج المركبة من منطقة محددة.'),
                ('تركيب احترافي', 'تمديدات مخفية ومرتبة على يد فنيينا.'),
                ('الدعم', 'مساعدة في التطبيقات والحسابات والأجهزة بعد التركيب.'),
            ],
            'faq': [
                ('هل يمكنني تتبّع مركباتي من جوالي؟', 'نعم. يعرض تتبّع GPS الموقع المباشر وسجل الرحلات على جوالك أو حاسوبك.'),
                ('هل تركّبون كاميرات السيارات؟', 'نعم &mdash; كاميرات أمامية وخلفية مع تمديدات مخفية ومرتبة.'),
                ('هل الخدمة للشركات أم للسيارات الخاصة؟', 'للاثنين. نركّب للسيارات الخاصة الفردية ولأساطيل الشركات.'),
            ],
        },
    },
    {
        'slug': 'electrical-services', 'region': 'uae', 'num': '11', 'related': None,
        'en': {
            'name': 'Electrical Services',
            'title': 'Electrical Wiring, Sensors &amp; Automation Services in Abu Dhabi &amp; UAE | Anqah Tech',
            'description': 'Electrical wiring, sensor installation and automated electrical systems for homes, villas and businesses in Abu Dhabi, Dubai and across the UAE.',
            'keywords': 'electrical services Abu Dhabi, electrician Abu Dhabi, electrical wiring Dubai, sensor installation UAE, smart switch installation, electrical maintenance UAE',
            'h1': 'Electrical services',
            'lead': 'Wiring, sensors and automated electrical systems &mdash; done safely and neatly, and ready for the smart devices you add later.',
            'offer': [
                ('Wiring &amp; points', 'New points, rewiring and circuits for homes, villas and offices.'),
                ('Sensor installation', 'Motion, light and occupancy sensors that switch lights and loads automatically.'),
                ('Smart switches', 'Switches and relays that can be controlled from your phone.'),
                ('Automation wiring', 'Wiring for gates, AC control, bells and other automated systems.'),
                ('Fault finding', 'Tracing and fixing tripping circuits and electrical faults.'),
                ('Maintenance', 'Planned checks and repairs under an annual maintenance contract.'),
            ],
            'faq': [
                ('Do you handle wiring for automation projects?', 'Yes &mdash; we wire gates, AC control, bells and other automated systems as part of the installation.'),
                ('Can you add sensors to switch lights automatically?', 'Yes. Motion and light sensors can switch lights and other loads on their own.'),
                ('Do you offer electrical maintenance?', 'Yes, under our annual maintenance contracts.'),
            ],
        },
        'ar': {
            'name': 'الخدمات الكهربائية',
            'title': 'التمديدات الكهربائية والحساسات والأنظمة الآلية في أبوظبي والإمارات | Anqah Tech',
            'description': 'تمديدات كهربائية وتركيب حساسات وأنظمة كهربائية آلية للمنازل والفلل والشركات في أبوظبي ودبي وجميع الإمارات.',
            'keywords': 'خدمات كهربائية أبوظبي, كهربائي أبوظبي, تمديدات كهربائية دبي, تركيب حساسات الإمارات, مفاتيح ذكية, صيانة كهربائية الإمارات',
            'h1': 'الخدمات الكهربائية',
            'lead': 'تمديدات وحساسات وأنظمة كهربائية آلية &mdash; تُنفّذ بأمان وإتقان، وجاهزة للأجهزة الذكية التي تضيفها لاحقًا.',
            'offer': [
                ('التمديدات والنقاط', 'نقاط جديدة وإعادة تمديد ودوائر للمنازل والفلل والمكاتب.'),
                ('تركيب الحساسات', 'حساسات حركة وضوء وإشغال تشغّل الإضاءة والأحمال تلقائيًا.'),
                ('المفاتيح الذكية', 'مفاتيح ومرحّلات يمكن التحكم بها من جوالك.'),
                ('تمديدات الأتمتة', 'تمديدات للبوابات والتحكم بالتكييف والأجراس والأنظمة الآلية الأخرى.'),
                ('تحديد الأعطال', 'تتبّع الدوائر التي تفصل والأعطال الكهربائية وإصلاحها.'),
                ('الصيانة', 'فحوصات وإصلاحات مخططة ضمن عقد صيانة سنوي.'),
            ],
            'faq': [
                ('هل تنفّذون التمديدات لمشاريع الأتمتة؟', 'نعم &mdash; نمدّد للبوابات والتحكم بالتكييف والأجراس والأنظمة الآلية ضمن التركيب.'),
                ('هل يمكنكم إضافة حساسات لتشغيل الإضاءة تلقائيًا؟', 'نعم. يمكن لحساسات الحركة والضوء تشغيل الإضاءة والأحمال الأخرى تلقائيًا.'),
                ('هل تقدّمون صيانة كهربائية؟', 'نعم، ضمن عقود الصيانة السنوية.'),
            ],
        },
    },
    {
        'slug': 'amc', 'region': 'uae', 'num': '12', 'related': None,
        'en': {
            'name': 'Annual Maintenance Contracts',
            'title': 'IT, CCTV &amp; Network Annual Maintenance Contracts (AMC) in Abu Dhabi &amp; UAE | Anqah Tech',
            'description': 'Annual maintenance contracts for IT, CCTV, networks, POS systems and automation in Abu Dhabi, Dubai and across the UAE: preventive visits, on-site support and priority response.',
            'keywords': 'AMC Abu Dhabi, IT AMC UAE, CCTV maintenance contract Abu Dhabi, network maintenance Dubai, POS maintenance UAE, annual maintenance contract IT',
            'h1': 'Annual maintenance contracts',
            'lead': 'Keep your IT, CCTV, network, POS and automation running &mdash; with planned preventive visits and on-site support when something goes wrong.',
            'offer': [
                ('Preventive maintenance', 'Scheduled visits to check, clean and update your systems before problems start.'),
                ('On-site support', 'A technician at your site when something needs hands-on attention.'),
                ('Remote support', 'Quick fixes over the phone or remote connection.'),
                ('Covered systems', 'IT, CCTV, networks, access control, POS and automation &mdash; one contract.'),
                ('Health reports', 'A record of what was checked, found and fixed on each visit.'),
                ('Priority response', 'AMC customers are attended to first.'),
            ],
            'faq': [
                ('What does an AMC cover?', 'Preventive visits, on-site and remote support for the systems listed in your contract &mdash; IT, CCTV, networks, POS or automation.'),
                ('Can one contract cover several systems?', 'Yes. You can combine IT, CCTV, network, POS and automation in one AMC.'),
                ('Do you maintain systems installed by others?', 'Yes, after an initial inspection to check their condition.'),
            ],
        },
        'ar': {
            'name': 'عقود الصيانة السنوية',
            'title': 'عقود الصيانة السنوية لتقنية المعلومات والكاميرات والشبكات في أبوظبي والإمارات | Anqah Tech',
            'description': 'عقود صيانة سنوية لتقنية المعلومات والكاميرات والشبكات وأنظمة نقاط البيع والأتمتة في أبوظبي ودبي وجميع الإمارات: زيارات وقائية ودعم في الموقع واستجابة ذات أولوية.',
            'keywords': 'عقد صيانة سنوي أبوظبي, صيانة تقنية المعلومات الإمارات, عقد صيانة كاميرات المراقبة, صيانة الشبكات دبي, صيانة أنظمة الكاشير',
            'h1': 'عقود الصيانة السنوية',
            'lead': 'حافظ على عمل أنظمة تقنية المعلومات والكاميرات والشبكات ونقاط البيع والأتمتة &mdash; بزيارات وقائية مخططة ودعم في الموقع عند حدوث أي مشكلة.',
            'offer': [
                ('الصيانة الوقائية', 'زيارات مجدولة لفحص أنظمتك وتنظيفها وتحديثها قبل حدوث المشكلات.'),
                ('الدعم في الموقع', 'فني في موقعك عندما يحتاج الأمر إلى تدخل مباشر.'),
                ('الدعم عن بُعد', 'إصلاحات سريعة عبر الهاتف أو الاتصال عن بُعد.'),
                ('الأنظمة المشمولة', 'تقنية المعلومات والكاميرات والشبكات والتحكم بالدخول ونقاط البيع والأتمتة &mdash; في عقد واحد.'),
                ('تقارير الحالة', 'سجل بما تم فحصه واكتشافه وإصلاحه في كل زيارة.'),
                ('أولوية الاستجابة', 'يُخدم عملاء عقود الصيانة أولًا.'),
            ],
            'faq': [
                ('ماذا يشمل عقد الصيانة؟', 'زيارات وقائية ودعم في الموقع وعن بُعد للأنظمة المذكورة في عقدك &mdash; تقنية المعلومات أو الكاميرات أو الشبكات أو نقاط البيع أو الأتمتة.'),
                ('هل يمكن لعقد واحد أن يشمل عدة أنظمة؟', 'نعم. يمكنك جمع تقنية المعلومات والكاميرات والشبكات ونقاط البيع والأتمتة في عقد واحد.'),
                ('هل تصونون أنظمة ركّبتها جهات أخرى؟', 'نعم، بعد فحص أولي للتأكد من حالتها.'),
            ],
        },
    },
]

# Dedicated POS hardware landing page (photos from images/products/pos-hardware/).
POS_MACHINES = {
    'slug': 'pos-machines', 'region': 'all', 'related': 'sello',
    'en': {
        'name': 'POS Machines',
        'title': 'POS Machines &amp; Hardware for Shops &amp; Restaurants in UAE, KSA &amp; India | Anqah Tech',
        'description': 'Buy complete POS machines in Abu Dhabi, Dubai, Riyadh and India: touch POS terminals, tablets, receipt printers, cash drawers and kitchen displays with SELLO software, installed and supported.',
        'keywords': 'POS machine UAE, POS machine Abu Dhabi, POS machine Dubai, buy POS system UAE, POS hardware UAE, touch POS terminal, receipt printer UAE, cash drawer, POS machine Saudi Arabia, billing machine India',
        'h1': 'POS machines &amp; hardware',
        'lead': 'Complete POS machines for shops, supermarkets, restaurants and caf&eacute;s &mdash; the hardware plus our SELLO software, installed, set up for your taxes and supported by one supplier.',
        'packages': [
            ('Retail &amp; supermarket', 'Touch POS terminal, barcode billing, receipt printer and cash drawer, with stock and purchasing in SELLO.'),
            ('Restaurant &amp; caf&eacute;', 'Counter terminal plus tablets for table orders and a kitchen display, with tables and modifiers in SELLO.'),
            ('Small shop &amp; mobile', 'SELLO Lite on an Android phone or tablet with a receipt printer &mdash; a full till with no internet needed.'),
        ],
        'faq': [
            ('Do you sell POS machines with software?', 'Yes. We supply complete POS systems &mdash; the hardware with our SELLO software installed and set up.'),
            ('Do you install and train staff?', 'Yes. Every POS package includes installation, product and tax setup, staff training and support.'),
            ('Can I use my existing computer or printer?', 'Often, yes. SELLO runs in the browser on most devices on your shop network; we check your equipment first.'),
            ('How much does a POS machine cost?', 'It depends on the devices and number of counters you need. Message us on WhatsApp for a quote for your shop.'),
        ],
    },
    'ar': {
        'name': 'أجهزة الكاشير',
        'title': 'أجهزة كاشير ونقاط بيع للمحلات والمطاعم في الإمارات والسعودية والهند | Anqah Tech',
        'description': 'اشترِ أجهزة كاشير متكاملة في أبوظبي ودبي والرياض والهند: أجهزة لمس وأجهزة لوحية وطابعات إيصالات وأدراج نقود وشاشات مطبخ مع برنامج SELLO، مع التركيب والدعم.',
        'keywords': 'جهاز كاشير الإمارات, جهاز كاشير أبوظبي, جهاز كاشير دبي, شراء نظام نقاط بيع, أجهزة نقاط البيع, جهاز كاشير باللمس, طابعة إيصالات, درج نقود, جهاز كاشير السعودية',
        'h1': 'أجهزة الكاشير ونقاط البيع',
        'lead': 'أجهزة كاشير متكاملة للمحلات والسوبرماركت والمطاعم والمقاهي &mdash; الأجهزة مع برنامجنا SELLO، مركّبة ومُعدّة لضرائبك ومدعومة من مورّد واحد.',
        'packages': [
            ('التجزئة والسوبرماركت', 'جهاز كاشير باللمس وفوترة بالباركود وطابعة إيصالات ودرج نقود، مع المخزون والمشتريات في SELLO.'),
            ('المطاعم والمقاهي', 'جهاز كاونتر مع أجهزة لوحية لطلبات الطاولات وشاشة مطبخ، مع الطاولات والإضافات في SELLO.'),
            ('المحلات الصغيرة والجوال', 'SELLO Lite على هاتف أو جهاز لوحي أندرويد مع طابعة إيصالات &mdash; كاشير كامل دون إنترنت.'),
        ],
        'faq': [
            ('هل تبيعون أجهزة كاشير مع البرنامج؟', 'نعم. نوفّر أنظمة نقاط بيع متكاملة &mdash; الأجهزة مع برنامج SELLO مثبّتًا ومُعدًّا.'),
            ('هل تركّبون وتدرّبون الموظفين؟', 'نعم. تشمل كل باقة التركيب وإعداد المنتجات والضريبة وتدريب الموظفين والدعم.'),
            ('هل يمكنني استخدام حاسوبي أو طابعتي الحالية؟', 'غالبًا نعم. يعمل SELLO في المتصفح على معظم الأجهزة على شبكة متجرك؛ ونفحص أجهزتك أولًا.'),
            ('كم سعر جهاز الكاشير؟', 'يعتمد على الأجهزة وعدد الكاونترات التي تحتاجها. راسلنا على واتساب لعرض سعر لمتجرك.'),
        ],
    },
}

# Shared page text
UI = {
    'en': {
        'services': 'Services', 'home': 'Home', 'offer': 'What we offer', 'how': 'How we work',
        'steps': [('Discover', 'We understand your needs, site and budget.'), ('Design', 'We plan the solution and give you a clear quote.'),
                  ('Install', 'We build, install and configure &mdash; neatly and on time.'), ('Support', 'Training, then ongoing support and AMC.')],
        'areas': 'Where we work', 'areas_all': 'From our base in Abu Dhabi we serve customers across the UAE, Saudi Arabia and India.',
        'areas_uae': 'On-site service across the UAE, from our base in Abu Dhabi.',
        'uae': ('United Arab Emirates', 'Abu Dhabi &middot; Dubai &middot; Sharjah &middot; Al Ain &middot; Ajman'),
        'ksa': ('Saudi Arabia', 'Riyadh &middot; Jeddah &middot; Dammam &middot; Makkah &middot; Madinah'),
        'ind': ('India', 'Kerala &middot; Bengaluru &middot; Chennai &middot; Mumbai &middot; Hyderabad'),
        'faq': 'Frequently asked questions', 'related': 'Related product', 'see': 'See {name}',
        'cta_h': 'Talk to us about {name}', 'cta_p': 'Tell us what you need &mdash; our team replies within 24 hours.',
        'wa': "Hello Anqah Tech, I'm interested in {name}. Please share more details.", 'quote': 'Get a quote',
        'other': 'Other services', 'all': 'All services',
        'hub_title': 'IT, Security, POS &amp; Automation Services in UAE, KSA &amp; India | Anqah Tech',
        'hub_desc': 'Anqah Tech services: web and app development, digital marketing, POS systems and machines, IT infrastructure, CCTV, access control, networks, automation, electrical and AMC.',
        'hub_h1': 'Our services', 'hub_lead': 'Software, security and automation for businesses, schools and homes &mdash; designed, installed and supported by one team in Abu Dhabi.',
        'hw_h': 'POS hardware we supply', 'pk_h': 'POS packages', 'incl': 'Every POS package includes',
        'hw_link': 'POS machines &amp; hardware',
    },
    'ar': {
        'services': 'الخدمات', 'home': 'الرئيسية', 'offer': 'ما نقدّمه', 'how': 'كيف نعمل',
        'steps': [('الاستكشاف', 'نفهم احتياجاتك وموقعك وميزانيتك.'), ('التصميم', 'نخطط الحل ونقدّم لك عرض سعر واضحًا.'),
                  ('التركيب', 'نبني ونركّب ونُعدّ &mdash; بإتقان وفي الوقت المحدد.'), ('الدعم', 'التدريب، ثم الدعم المستمر وعقود الصيانة.')],
        'areas': 'أين نعمل', 'areas_all': 'من مقرّنا في أبوظبي نخدم العملاء في الإمارات والسعودية والهند.',
        'areas_uae': 'خدمة في الموقع في جميع أنحاء الإمارات، من مقرّنا في أبوظبي.',
        'uae': ('الإمارات العربية المتحدة', 'أبوظبي &middot; دبي &middot; الشارقة &middot; العين &middot; عجمان'),
        'ksa': ('المملكة العربية السعودية', 'الرياض &middot; جدة &middot; الدمام &middot; مكة المكرمة &middot; المدينة المنورة'),
        'ind': ('الهند', 'كيرالا &middot; بنغالور &middot; تشيناي &middot; مومباي &middot; حيدر أباد'),
        'faq': 'الأسئلة الشائعة', 'related': 'المنتج المرتبط', 'see': 'شاهد {name}',
        'cta_h': 'تحدّث معنا عن {name}', 'cta_p': 'أخبرنا بما تحتاجه &mdash; يردّ فريقنا خلال 24 ساعة.',
        'wa': 'مرحبًا Anqah Tech، أنا مهتم بخدمة {name}. أرجو تزويدي بالتفاصيل.', 'quote': 'اطلب عرض سعر',
        'other': 'خدمات أخرى', 'all': 'كل الخدمات',
        'hub_title': 'خدمات تقنية المعلومات والأمن ونقاط البيع والأتمتة في الإمارات والسعودية | Anqah Tech',
        'hub_desc': 'خدمات Anqah Tech: تطوير المواقع والتطبيقات والتسويق الرقمي وأنظمة وأجهزة نقاط البيع والبنية التحتية والكاميرات والتحكم بالدخول والشبكات والأتمتة والكهرباء وعقود الصيانة.',
        'hub_h1': 'خدماتنا', 'hub_lead': 'برمجيات وأمن وأتمتة للشركات والمدارس والمنازل &mdash; يصمّمها ويركّبها ويدعمها فريق واحد في أبوظبي.',
        'hw_h': 'أجهزة نقاط البيع التي نوفّرها', 'pk_h': 'باقات نقاط البيع', 'incl': 'تشمل كل باقة نقاط بيع',
        'hw_link': 'أجهزة الكاشير ونقاط البيع',
    },
}
